margin: 0.2
data:
  num_workers: 12
  extract: false
  prepare: false
  iterable: false
  target_size:
  - 180
  - 100
  train:
    force_cache: false
    batch_size: 8
    jitter: false
    duration: 2.3
    shuffle: true
  val:
    force_cache: false
    batch_size: 8
    jitter: false
    duration: 2.3
  test:
    force_cache: false
    batch_size: 8
    jitter: false
    duration: 2.3
video:
  static: true
  pretrained: true
  project: true
audio:
  path: data/in/wav2vec/wav2vec_small.pt
  pretrained: true
  freeze_feature_extractor: true
  freeze_encoder_layers: 3
  pooling: attention
training:
  trainer_args:
    gpus:
    - 1
    auto_select_gpus: false
    accumulate_grad_batches: 8
    precision: 16
optimizer:
  lr: 0.0001
  warmup: 0.1
  schedule: warmup_linear
  t_total: 10000
git_commit: 4f0c4ae9c3b805c622dc66d266ae9f8f5e907432
