margin: 0.2
data:
  num_workers: 12
  extract: false
  prepare: false
  iterable: false
  target_size:
  - 180
  - 100
  audio_sample_rate: 44100
  train:
    force_cache: false
    batch_size: 8
    jitter: true
    jitter_sd: 0.5
    duration: 2.3
    shuffle: true
  val:
    force_cache: false
    batch_size: 8
    jitter: false
    duration: 2.3
  test:
    force_cache: false
    batch_size: 8
    jitter: false
    duration: 2.3
video:
  static: true
  pretrained: false
  project: true
  pooling: attention
audio:
  path: data/in/wav2vec/wav2vec_small.pt
  pretrained: true
  freeze_feature_extractor: false
  freeze_encoder_layers: null
  pooling: attention
  full: true
training:
  trainer_args:
    gpus: 1
    auto_select_gpus: false
    accumulate_grad_batches: 8
    precision: 16
optimizer:
  lr: 0.0001
  warmup: 0.1
  schedule: warmup_linear
  t_total: 15000
git_commit: 0071a7ad07b58fd9b5f663e0246f0272f56cf634
