margin: 0.2
data:
  num_workers: 12
  extract: false
  prepare: false
  iterable: false
  force_cache: false
  target_size:
  - 180
  - 100
  train:
    batch_size: 6
    jitter: false
    shuffle: true
  val:
    batch_size: 6
  test:
    batch_size: 8
video:
  pretrained: false
  project: true
  version: r2plus1d_18
  pooling: attention
audio:
  path: data/in/wav2vec/wav2vec_small.pt
  pretrained: false
  freeze_feature_extractor: false
  freeze_encoder_layers: null
  pooling: attention
training:
  trainer_args:
    gpus:
    - 2
    auto_select_gpus: false
    accumulate_grad_batches: 8
optimizer:
  lr: 0.0001
  warmup: 0.1
  schedule: warmup_linear
  t_total: 32640
git_commit: a95eef598658d2ef72dad9e9d53436ffb2515eee
