margin: 0.2
data:
  num_workers: 12
  extract: false
  prepare: false
  iterable: false
  target_size:
  - 180
  - 100
  train:
    force_cache: false
    batch_size: 8
    jitter: true
    jitter_sd: 0.5
    duration: 2.3
    shuffle: true
  val:
    force_cache: false
    batch_size: 8
    jitter: false
    duration: 2.3
  test:
    force_cache: false
    batch_size: 8
    jitter: false
    duration: 2.3
video:
  pretrained: true
  project: true
  version: r2plus1d_18
  pooling: attention
audio:
  path: data/in/wav2vec/wav2vec_small.pt
  pretrained: true
  freeze_feature_extractor: true
  freeze_encoder_layers: 12
  pooling: attention
  full: true
training:
  trainer_args:
    gpus: 1
    auto_select_gpus: false
    accumulate_grad_batches: 8
    precision: 16
optimizer:
  lr: 0.0001
  warmup: 0.1
  schedule: warmup_linear
  t_total: 15000
git_commit: 1e958031ba2ef8d7b4a03b9c941b45221477a85b
