margin: 0.2
data:
  num_workers: 8
  extract: false
  prepare: false
  iterable: false
  force_cache: false
  target_size:
  - 360
  - 200
  train:
    batch_size: 6
    duration: 3.2
    shuffle: true
    jitter: false
  val:
    batch_size: 8
    duration: 3.2
    jitter: false
  test:
    batch_size: 8
video:
  pretrained: true
  project: true
  version: r2plus1d_18
  pooling: attention
audio:
  path: data/in/wav2vec/wav2vec_small.pt
  pretrained: true
  freeze_feature_extractor: true
  freeze_encoder_layers: 3
  pooling: attention
training:
  trainer_args:
    gpus:
    - 0
    auto_select_gpus: false
    precision: 16
    accumulate_grad_batches: 10
    reload_dataloaders_every_n_epochs: 1
optimizer:
  lr: 0.0001
  warmup: 0.1
  schedule: warmup_linear
  t_total: 10000
git_commit: 362818e513b90b5e6a402bd7cf900043601745d6
